export const integrationSectionBar = [
  {
    icon_image: "/src/assets/img/icons/shopping-cart.png",
    name: "Stock",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
  {
    icon_image: "/src/assets/img/icons/truck.png",
    name: "Supply",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
];

export const menuSectionBar = [
  {
    icon_image: "/src/assets/img/icons/category-2.png",
    name: "Dashboard",
    url: "",
    active: false,
    notification: true,
    notif_count: 4,
  },
  {
    icon_image: "/src/assets/img/icons/battery-full.png",
    name: "Stock",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
  {
    icon_image: "/src/assets/img/icons/profile-2user.png",
    name: "Customer",
    url: "",
    active: true,
    notification: false,
    notif_count: 0,
  },
  {
    icon_image: "/src/assets/img/icons/reserve.png",
    name: "Restaurant",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
  {
    icon_image: "/src/assets/img/icons/mouse-square.png",
    name: "Design",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
  {
    icon_image: "/src/assets/img/icons/document-normal.png",
    name: "Report",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
  {
    icon_image: "/src/assets/img/icons/user-square.png",
    name: "Role & Admin",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
  {
    icon_image: "/src/assets/img/icons/candle.png",
    name: "Settings",
    url: "",
    active: false,
    notification: false,
    notif_count: 0,
  },
];
